version: "3.9"

volumes:
  data:

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  app:
    depends_on:
      postgres:
        condition: service_healthy
    build: .
    command: "sleep infinity"
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
