[package]
name = "db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
sqlx = { version = "0.7.0-alpha.2", features = ["runtime-tokio-rustls", "postgres"] }
