version: "3.9"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  app:
    image: tobiaszimmer/graph-project:latest
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
